### ISSUE TITLE
Dependencies from an outside scope not yet created

### ISSUE THREAD

**Issue by undermark5** [InsertKoinIO/koin-annotations#117]
**Describe the bug**
When declaring a koin managed object, if there is an argument that is scoped, the generated code uses `getScope` rather than `getOrCreateScope`, which can lead to failures if the scope hasn't already been opened.

**To Reproduce**
1. define a custom scope (either generated or manually, doesn't matter)
2. define a type within the scope
3. define a class with an argument of the type defined above
4. start koin without starting the scope
5. get an instance of the managed object defined in step 3

**Expected behavior**
No crash should occur

**Koin project used and used version (please complete the following information):**
 `koin-annotations 1.3.0`

**Comment by arnaudgiuliani** [comment]
The problem here is that `getOrCreateScope()` need all info to create a scope + the scopeId. You have to give all details to create a scope instance. Scope creation is a runtime operation. What specify `@ScopeId` is that you'ill find this instance in this scopeId. 

Rather this way you would need `@Scope` and `@ScopeId` to tag your attribute. Not convinced that this is where we can give an asnwer.

**Comment by undermark5** [comment]
We can probably close this, as it's probably a situation of misusing/misunderstanding how scopes should function/behave.
